# Iris Dataset

## Importação dos dados

In [4]:
from sklearn.datasets import load_iris
iris = load_iris()
#print(iris)

comprimento sepala, largura sepala, comprimento petala, largura etala
sepal_length, sepal_width, petal_length, petal_width
[5.7 2.8 4.5 1.3]

['setosa' 'versicolor' 'virginica']

### Observações

In [6]:
#print(iris.data)
print(type(iris.data))

<class 'numpy.ndarray'>


### Target

In [8]:
#print(iris.target)
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


#### Shape das observações

In [9]:
print(iris.data.shape)
#150 observações e 4 atributos

(150, 4)


#### Shape do Target

In [10]:
print(iris.target.shape)

(150,)


In [22]:
x = iris.data
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [14]:
y = iris.target
#print(y)

#### Modelo estatítisco KNN

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

### Treinar a Máquina

In [21]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=1)

### Fazer previsões

In [27]:
knn.predict([[5.1, 3.5, 1.4, 0.2]]) #espécie 1 - Setosa[0]

array([0])

In [29]:
knn.predict([[5.9, 3.,  4.2, 1.5]]) #espécie 2 - Versicolor[1]

array([1])

In [31]:
species = knn.predict([[5.1, 3.5, 1.4, 0.2]])[0]
print(iris.target_names[species])

setosa


### Separar os dados em dois grupos

In [34]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [36]:
print(x_test.shape)
print(x_train.shape)

(38, 4)
(112, 4)


### Avaliação da performance do modelo

In [38]:
knn.fit(x_train, y_train)
previsoes = knn.predict(x_test)
#print(previsoes)

[1 0 1 2 1 2 1 1 2 1 2 0 0 2 1 0 2 1 2 1 0 2 0 2 2 0 0 1 1 0 2 1 2 1 0 2 0
 1]


In [40]:
from sklearn import metrics
acertos = metrics.accuracy_score(y_test, previsoes)
print(acertos)

0.9736842105263158


# Modelo Estatístico de Regressão Logística
## Uso de Machine Learning para previsões categóricas
### Deve ser usado com classificações binárias, mas pode ser bem usado com mais variáveis (uso de modelo one vs all)
#### Aplicação do modelo de regressão logística

In [45]:
from sklearn.linear_model import LogisticRegression
#logreg = LogisticRegression(multi_class="ovr") já é o padrão one vs all
logreg = LogisticRegression()
logreg.fit(x_train, y_train)
previsoes_logreg = logreg.predict(x_test)
acertos_logreg = metrics.accuracy_score(y_test, previsoes_logreg)
print(acertos_logreg)

0.9736842105263158


In [42]:
#print(logreg.predict([[6.2, 3.4, 5.4, 2.3]]))
#print(logreg.predict_proba([[6.2, 3.4, 5.4, 2.3]]))